### ISSUE TITLE
Port index of discoverable taps and targest to dedicated MeltanoHub website

### ISSUE THREAD

**Issue by MeltyBot** [meltano/hub#5]
Migrated from GitLab: https://gitlab.com/meltano/hub/-/issues/4

Originally created by @DouweM on 2021-02-24 16:17:33

---

This will be the Singer equivalent of PyPI, Docker Hub, or dbt Hub.

Part of this is defining the first draft of the spec for taps and targets https://gitlab.com/meltano/singerhub/-/issues/14

- [x] Convert all targets to YAML
- [x] Convert all taps to YAML
- [x] Validate existing YAML is clean w/ no meltano-specific items https://gitlab.com/meltano/hub/-/merge_requests/1
  -  [x] Generate JSON schema to validate against (ideally single schema for both taps / targets) [#14](https://gitlab.com/meltano/hub/-/issues/14) 
- [x] Make HTML more sensible (no `ul`s with `h3`s and `p`s without `li`) @DouweM 
- [x] Index
  - [x] Large Banner welcoming Singer community and linking to hub.meltano.com/singer ([#21](https://gitlab.com/meltano/hub/-/issues/21))
  - [x] 3 Plugin categories - Extractors / Loaders / Utilities
    - [ ] Highlight a few that we support? Link to docs on what those are?
- [x] Add pages for `/singer`, `/taps`, `/targets` [#21](https://gitlab.com/meltano/hub/-/issues/21)
- [x] Tap and target lists
  - [x] Sort taps and targets by name
  - [x] Add logos grid @DouweM  https://gitlab.com/meltano/hub/-/merge_requests/4
- [ ] Details pages
  - [x] Break discovery.yml into separate meltano-specific files for generation of
  - [x] Add "| MeltanoHub" to title
  - [x] Add description
  - [ ] Add permalink?
  - [x] Move over from subpages under https://meltano.com/plugins/extractors/ and https://meltano.com/plugins/loaders/ to hub.meltano.com/plugins/extractors and hub.meltano.com/plugins/loaders:
    - [x] Introduction
      - [x] Link to source API docs
    - [x] Maintenance
      - [ ] Suggestion to find a fork/variant when status is responsive
      - [x] Get maintainer data from maintainers.yml
    - [x] Installation
      - [x] `pip install <pip_url>`
      - [x] `meltano add X --variant Y`
    - [x] Settings
      - [x] Default value
      - [x] Descriptions, which in some cases is more complete than what's in `discovery.yml`
      - On Meltano pages:
        - [x] Env var
        - [x] `meltano config...`
    - [x] Troubleshooting

**Comment by MeltyBot** [comment]
[View 57 previous comments from the original issue on GitLab](https://gitlab.com/meltano/hub/-/issues/4)
