### ISSUE TITLE
Add missing settings in high value places

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#936]
These are taps/targets that exist on the hub, are the default variant, have anonymous `add` usage in the last 6 months, but dont have any settings available. Not having settings makes for a pretty bad experience since you dont know what values it needs once its installed in your project, meaning you need to go read the repo readme or code.

Following https://github.com/meltano/hub/pull/935 we can run the hub_utils script for these taps and try to extract or prompt for missing settings so they're in good enough shape for users.

These are in order of most add requests:

- [x] tap-redshift	https://github.com/datadotworld/tap-redshift (default variant replaced with https://github.com/Monad-Inc/tap-redshift since it wouldnt install)
- [x] target-azureblobstorage	https://github.com/shrutikaponde-vc/target-azureblobstorage
- [x] tap-google-search-console	https://github.com/singer-io/tap-google-search-console
- [x] tap-mambu	https://github.com/singer-io/tap-mambu (failed to install for me requiring python >=3.9)
- [x] tap-exchangeratesapi	https://github.com/singer-io/tap-exchangeratesapi
- [x] tap-mailchimp	https://github.com/lovepopcards/tap-mailchimp
- [x] tap-exchangeratehost	https://github.com/anelendata/tap-exchangeratehost
- [x] tap-intercom	https://github.com/singer-io/tap-intercom
- [x] tap-db2	https://github.com/singer-io/tap-db2
- [x] tap-parquet	https://github.com/dataops-tk/tap-parquet
- [x] tap-fixerio	https://github.com/singer-io/tap-fixerio
- [x] tap-appstore	https://github.com/miroapp/tap-appstore
- [x] tap-twitter	https://github.com/bernietai/tap-twitter
- [ ] tap-prometheus	https://github.com/miroapp/tap-prometheus (fails - issue https://github.com/meltano/hub/issues/941)
- [x] tap-loopreturns	https://github.com/LoopReturns/tap-loopreturns
- [x] tap-gmail-csv	https://github.com/food-spotter/tap-gmail-csv
- [x] tap-mailgun	https://github.com/streetteam/tap-mailgun
- [x] tap-gmail	https://github.com/Mashey/tap-gmail (default replaced with https://github.com/kgpayne/tap-gmail)
- [x] tap-twitter-ads	https://github.com/singer-io/tap-twitter-ads
- [x] tap-dayforce	https://github.com/goodeggs/tap-dayforce
- [x] tap-powerbi-metadata	https://github.com/dataops-tk/tap-powerbi-metadata
- [x] tap-appsflyer	https://github.com/singer-io/tap-appsflyer
- [x] tap-activecampaign	https://github.com/singer-io/tap-activecampaign
- [x] tap-twinfield	https://github.com/Yoast/singer-tap-twinfield
- [x] tap-procore	https://github.com/hotgluexyz/tap-procore
- [x] ~tap-github-org-projects	https://github.com/rossmcdonald/tap-github-org-projects~
- [x] tap-pipedrive	https://github.com/singer-io/tap-pipedrive
- [ ] tap-athena	https://github.com/MeltanoLabs/tap-athena (erroring https://github.com/MeltanoLabs/tap-athena/issues/9 and https://github.com/meltano/hub/issues/995)
- [x] tap-bls	https://github.com/frasermarlow/tap-bls
- [x] tap-sendgrid	https://github.com/singer-io/tap-sendgrid
- [x] tap-campaign-monitor	https://github.com/singer-io/tap-campaign-monitor
- [x] tap-acuite	https://github.com/FostersData/tap-acuite
- [x] tap-pardot	https://github.com/singer-io/tap-pardot
- [x] tap-paypal	https://github.com/Yoast/singer-tap-paypal
- [ ] tap-facebook-posts	https://github.com/rowanv/tap-facebook-posts (fails to install https://github.com/meltano/hub/issues/988)
- [x] tap-youtube-analytics	https://github.com/singer-io/tap-youtube-analytics
- [x] tap-exacttarget	https://github.com/singer-io/tap-exacttarget
- [x] tap-greenhouse	https://github.com/codyss/tap-greenhouse (install fails https://github.com/meltano/hub/issues/993)
- [x] tap-holidays	https://github.com/goodeggs/tap-holidays
- [x] tap-harvest	https://github.com/singer-io/tap-harvest
- [x] tap-freshdesk	https://github.com/singer-io/tap-freshdesk
- [x] tap-dbt	https://github.com/meltanolabs/tap-dbt
- [x] tap-platformpurple	https://github.com/singer-io/tap-platformpurple
- [ ] tap-recruitee	https://github.com/Tahasadiki/tap-recruitee (install fails https://github.com/meltano/hub/issues/989)
- [x] tap-sumologic	https://github.com/splitio/tap-sumologic
- [ ] tap-purecloud	https://github.com/rumeau/tap-purecloud (hard fork of singer-io), potentially use https://github.com/Pathlight/tap-purecloud instead which is the most active based on the network graph, theres also several other varaints listed to compare. Issue to re-evaluate https://github.com/meltano/hub/issues/996
- [x] tap-zuora	https://github.com/transferwise/pipelinewise-tap-zuora
- [x] tap-zendesk-chat	https://github.com/singer-io/tap-zendesk-chat
- [x] tap-closeio	https://github.com/singer-io/tap-closeio
- [x] tap-linkedin-ads	https://github.com/singer-io/tap-linkedin-ads
- [x] tap-snapchat-ads	https://github.com/singer-io/tap-snapchat-ads
- [x] tap-strava	https://github.com/briansloane/tap-strava
- [ ] tap-abcfinancial	https://github.com/dmzobel/tap-abcfinancial (failed installing https://github.com/meltano/hub/issues/991)
- [x] tap-square	https://github.com/Kalai-Wavicle/tap-square
- [x] tap-saasoptics	https://github.com/anelendata/tap-saasoptics
- [x] tap-twitter-streams	https://github.com/pbegle/tap-twitter-streams
- [x] tap-fullstory	https://github.com/singer-io/tap-fullstory
- [x] tap-kustomer	https://github.com/singer-io/tap-kustomer
- [x] target-stitch	https://github.com/singer-io/target-stitch
- [x] tap-amazon-advertising	https://github.com/dbt-labs/tap-amazon-advertising
- [x] tap-newrelic	https://github.com/fixdauto/tap-newrelic
- [x] tap-sklik	https://github.com/polar-analytics/tap-sklik
- [x] tap-yotpo	https://github.com/singer-io/tap-yotpo
- [x] tap-helpscout	https://github.com/singer-io/tap-helpscout
- [x] tap-outbrain	https://github.com/dbt-labs/tap-outbrain
- [x] tap-workday-raas	https://github.com/singer-io/tap-workday-raas
- [ ] tap-amazon-mws	https://github.com/dbt-labs/tap-amazon-mws (legacy API https://hub.meltano.com/extractors/tap-amazon-mws replaced with amazon selling partners) Issue to track this https://github.com/meltano/hub/issues/998
- [x] tap-adyen	https://github.com/Yoast/singer-tap-adyen
- [x] tap-domo	https://github.com/Mashey/tap-domo
- [x] tap-lever	https://github.com/dbt-labs/tap-lever
- [x] tap-iterable	https://github.com/lambtron/tap-iterable
- [x] target-cassandra	https://github.com/coeff/target-cassandra
- [x] tap-looker	https://github.com/singer-io/tap-looker
- [x] tap-urban-airship	https://github.com/singer-io/tap-urban-airship
- [x] tap-eloqua	https://github.com/singer-io/tap-eloqua
- [x] tap-dynamics	https://github.com/dreamdata-io/tap-dynamics
- [x] tap-redash	https://github.com/domb16/tap-redash
- [x] tap-recurly	https://github.com/lambtron/tap-recurly
- [x] tap-harvest-forecast	https://github.com/singer-io/tap-harvest-forecast
- [x] tap-okta	https://github.com/isabella232/tap-okta
- [x] target-datadotworld	https://github.com/datadotworld/target-datadotworld
- [x] tap-sailthru	https://github.com/singer-io/tap-sailthru
- [x] tap-impact	https://github.com/singer-io/tap-impact
- [x] tap-chargify	https://github.com/singer-io/tap-chargify
- [ ] tap-clockify	https://github.com/immuta/tap-clockify (fails to install https://github.com/immuta/tap-clockify/issues/10 and https://github.com/meltano/hub/issues/997)

**Comment by tayloramurphy** [comment]
This is great - we should cross-post this for Taptoberfest as well.

**Comment by pnadolny13** [comment]
The query is:

```
SELECT *
FROM prod.MELTANO_HUB.FACT_VARIANT_HUB_METRICS 
LEFT JOIN prep.MELTANOHUB.STG_MELTANOHUB__PLUGINS
	ON FACT_VARIANT_HUB_METRICS.repo = STG_MELTANOHUB__PLUGINS.repo
WHERE COALESCE(FACT_VARIANT_HUB_METRICS.all_projects, 0) != 0
AND STG_MELTANOHUB__PLUGINS.is_default AND settings = []::ARRAY
ORDER BY FACT_VARIANT_HUB_METRICS.all_projects DESC;
```

**Comment by pnadolny13** [comment]
I'm closing this issue since all settings have been updated except for 7 which have bugs or other issues. I created individual issues for each of those to track the bug/problem.
